import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../src/components/Header";
import { SunCalc } from "../src/components/SunCalc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shatsam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SunCalc /> 
    </>
  );
};

export default Home;
